### ISSUE TITLE
Many functions but vignette does show how to use them. - DECIDE

### ISSUE THREAD

**Issue by schoolAccountMajaG** [lhenneman/hyspdisp#34]
The package has many functions. The vignette does not show how to use all of them and the object documentation is not detailed enough.  This might be a bit confusing. It would be good to revise the functions and see if there are any that are redundant. Which ones are the key ones? Which ones should be in the vignette and for which ones should have better documentation.

**Comment by lhenneman** [comment]
Some of the functions are currently superfluous, and can be deleted: R/hyspdisp.R and R/hyspdisp_fac_model.R (this is the serial version of hyspdisp_fac_model_parallel.R, but I stopped developing it because I hadn't found any reasons to run serially).

Do we need examples in the vignette for functions that shouldn't be called by the user, e.g., R/trim_pbl.R and R/trim_zero?

**Comment by cchoirat** [comment]
> Do we need examples in the vignette for functions that shouldn't be called by the user, e.g., R/trim_pbl.R and R/trim_zero?

I'd say no.

**Comment by schoolAccountMajaG** [comment]
implemented
