### ISSUE TITLE
Decide what functions we do not need 

### ISSUE THREAD

**Issue by schoolAccountMajaG** [lhenneman/hyspdisp#42]
Agreed with Lucas, that he would look at the functions that are unused.

**Comment by lhenneman** [comment]
I found three unused functions:
define_inputtimes.R (obsolete because of define_inputs.R)
hyspdisp.R
hyspdisp_fac_model.R (obsolete because of hyspdisp_fac_model_parallel.R -- is there a way to allow hyspdisp_fac_model_parallel.R to be applied both serial and parallel applications?)

There are others that are only called as utilities to main functions:
link_zip.R
trim_pbl.R
trim_zero.R
negate_util.R

**Comment by schoolAccountMajaG** [comment]
Thanks a lot! 

> hyspdisp_fac_model.R (obsolete because of hyspdisp_fac_model_parallel.R -- is there a way to allow hyspdisp_fac_model_parallel.R to be applied both serial and parallel applications?

I will look into that.

**Comment by schoolAccountMajaG** [comment]
https://github.com/garbulinskamaja/disperseR/blob/master/R/run_fac_parallel.R does the job in `disperseR` can be run serial by setting `mc.cores==1`
